version: '2'

services:
  nginx:
    container_name: nginx
    build: ./nginx
    links:
      - api1:api1
      - api2:api2
      - api3:api3
      - web:web
    ports:
      - "80:80"
      - "443:443"
  api1:
    container_name: api-1
    build: ./api
    ports:
      - "8082"
  api2:
    container_name: api-2
    build: ./api
    ports:
      - "8082"
  api3:
    container_name: api-3
    build: ./api
    ports:
      - "8082"
  web:
    container_name: web
    build: ./web
    ports:
      - "8082"
  dbseeder:
    container_name: dbseeder
    depends_on:
      - db
    build:
      context: ./dbseeder
      dockerfile: ./Dockerfile
  db:
    container_name: db
    image: rethinkdb
    ports:
      - "8080"
      - "28015"
      - "29015"
    volumes:
      - ./data:/data
