version: '2'

services:
  nginx:
    container_name: nginx
    build: ./nginx
    links:
      - rdb:rdb
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nexgen-network
  rdb:
    container_name: rdb
    image: rethinkdb
    ports:
      - "8080"
      - "28015"
      - "29015"
    volumes:
      - ./data:/data
    networks:
      - nexgen-network

networks:
  nexgen-network:
    driver: bridge
